version: "3"

services:
  #MongoDB Service
  mongodb:
    image: mongo:3.6.8
    container_name: mongodb-local
    environment:
      MONGO_INITDB_ROOT_USERNAME: productListUser
      MONGO_INITDB_ROOT_PASSWORD: productListPassword
      MONGO_INITDB_DATABASE: promotions
    ports:
      - 27017:27017

  #MongoDB seed
  mongo_seed:
    image: mongo:3.6.8
    restart: on-failure
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command: /mongo-seed/import.sh

  #Back-end Spring Boot Application
  search-product-app:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./search-product-ms
    container_name: search-product-app

    #Environment variables for Spring Boot Application.
    environment:
      - MONGODB_USERNAME=productListUser
      - MONGODB_PASSWORD=productListPassword
      - MONGODB_DATABASE=promotions
      - MONGODB_PORT=27017
      - MONGODB_HOST=mongodb-local
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - mongo_seed
  # Fron-end Angular Application
  search-engine-app:
    build: ./search-engine-front
    container_name: search-engine-app
    ports:
      - 4200:80
    links:
      - search-product-app